name: Trigger Vercel Deployment

on:
  workflow_dispatch:  # Manual trigger only

jobs:
  notify-vercel:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Ping Vercel (Optional)
        run: |
          # Just a dummy step to ensure workflow runs
          echo "Triggering Vercel deployment via GitHub integration..."